/** Shared DISCO display names — aligned with belpower-frontend */
export const DISCO_NAMES: Record<string, string> = {
  ABUJA: 'Abuja Electricity Distribution Company',
  ACCESSPOWER: 'ACCESSPOWER',
  EKO: 'Eko Electricity Distribution Company',
  IKEJA: 'Ikeja Electricity Distribution Company',
  IBADAN: 'Ibadan Electricity Distribution Company',
  ENUGU: 'Enugu Electricity Distribution Company',
  PH: 'Port Harcourt Electricity Distribution Company',
  JOS: 'Jos Electricity Distribution',
  KADUNA: 'Kaduna Electricity Distribution Company',
  KANO: 'Kano Electricity Distribution Company',
  BH: 'Brains & Hammers, Life Camp',
  APLE: 'Aba Power Limited Electricity Company',
  BENIN: 'Benin Electricity Distribution Company',
  KAIDA: 'Streamaco',
  KOIOS: 'KOIOS Renewable Energy',
  YOLA: 'Yola Electricity Distribution Company',
  SAO_ENERGIES: 'Sao Energies',
  DARWAY_COAST: 'Darway Coast',
  BUY_POWER_1: 'Buypower X Streamaco 1',
  BUY_POWER_2: 'Buypower X Streamaco 2',
  BUY_POWER_3: 'Buypower X Streamaco 3',
  KAIDA_STS: 'STEAMACO-STS',
  ASHIPA: 'Ashipa',
  MASKH: 'Maskh',
  ARAROMI: 'Araromi Obu',
  UKNIAF: 'EEDC UKNIAF Agborou-Onuorie Pilot',
  BUC: 'Bonny Utility Company',
  ENERCON: 'Enercon Nigeria',
  MEGAPLAZA: 'Mega Plaza',
  NESCO: 'Nigerian Electricity Supply Corporation',
  CENECO: 'Aiyegun',
  IKEDC: 'Ikeja Electricity Distribution Company',
  EKEDC: 'Eko Electricity Distribution Company',
  AEDC: 'Abuja Electricity Distribution Company',
  IBEDC: 'Ibadan Electricity Distribution Company',
  PHED: 'Port Harcourt Electricity Distribution Company',
  KAEDC: 'Kaduna Electricity Distribution Company',
  KEDCO: 'Kano Electricity Distribution Company',
  JEDC: 'Jos Electricity Distribution',
  BEDC: 'Benin Electricity Distribution Company',
  YEDC: 'Yola Electricity Distribution Company',
};

export function getDiscoDisplayName(code: string): string {
  const key = code?.toUpperCase().replace(/\s/g, '_') ?? '';
  return DISCO_NAMES[key] ?? code;
}
